# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configure_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 279)
        Form.setMinimumSize(QtCore.QSize(541, 279))
        Form.setMaximumSize(QtCore.QSize(541, 279))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/configure"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background:white")
        self.spectrogram_group = QtWidgets.QGroupBox(Form)
        self.spectrogram_group.setGeometry(QtCore.QRect(310, 10, 221, 171))
        self.spectrogram_group.setObjectName("spectrogram_group")
        self.stft_nfft_cobox = QtWidgets.QComboBox(self.spectrogram_group)
        self.stft_nfft_cobox.setGeometry(QtCore.QRect(140, 20, 69, 22))
        self.stft_nfft_cobox.setObjectName("stft_nfft_cobox")
        self.stft_wtype_cobox = QtWidgets.QComboBox(self.spectrogram_group)
        self.stft_wtype_cobox.setGeometry(QtCore.QRect(140, 50, 69, 22))
        self.stft_wtype_cobox.setObjectName("stft_wtype_cobox")
        self.stft_hlength_cobox = QtWidgets.QComboBox(self.spectrogram_group)
        self.stft_hlength_cobox.setGeometry(QtCore.QRect(140, 80, 69, 22))
        self.stft_hlength_cobox.setObjectName("stft_hlength_cobox")
        self.stft_wlength_cobox = QtWidgets.QComboBox(self.spectrogram_group)
        self.stft_wlength_cobox.setGeometry(QtCore.QRect(140, 110, 69, 22))
        self.stft_wlength_cobox.setObjectName("stft_wlength_cobox")
        self.stft_nfft_label = QtWidgets.QLabel(self.spectrogram_group)
        self.stft_nfft_label.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.stft_nfft_label.setObjectName("stft_nfft_label")
        self.stft_wtype_label = QtWidgets.QLabel(self.spectrogram_group)
        self.stft_wtype_label.setGeometry(QtCore.QRect(40, 50, 81, 21))
        self.stft_wtype_label.setObjectName("stft_wtype_label")
        self.stft_hlength_label = QtWidgets.QLabel(self.spectrogram_group)
        self.stft_hlength_label.setGeometry(QtCore.QRect(40, 80, 81, 21))
        self.stft_hlength_label.setObjectName("stft_hlength_label")
        self.stft_wlength_label = QtWidgets.QLabel(self.spectrogram_group)
        self.stft_wlength_label.setGeometry(QtCore.QRect(40, 110, 81, 21))
        self.stft_wlength_label.setObjectName("stft_wlength_label")
        self.log_stft_cbox = QtWidgets.QCheckBox(self.spectrogram_group)
        self.log_stft_cbox.setGeometry(QtCore.QRect(90, 140, 121, 17))
        self.log_stft_cbox.setChecked(True)
        self.log_stft_cbox.setObjectName("log_stft_cbox")
        self.spectrum_group = QtWidgets.QGroupBox(Form)
        self.spectrum_group.setGeometry(QtCore.QRect(310, 190, 221, 80))
        self.spectrum_group.setObjectName("spectrum_group")
        self.spectrum_nfft_cobox = QtWidgets.QComboBox(self.spectrum_group)
        self.spectrum_nfft_cobox.setGeometry(QtCore.QRect(140, 30, 69, 22))
        self.spectrum_nfft_cobox.setObjectName("spectrum_nfft_cobox")
        self.spectrum_nfft_label = QtWidgets.QLabel(self.spectrum_group)
        self.spectrum_nfft_label.setGeometry(QtCore.QRect(40, 30, 81, 21))
        self.spectrum_nfft_label.setObjectName("spectrum_nfft_label")
        self.mic_group = QtWidgets.QGroupBox(Form)
        self.mic_group.setGeometry(QtCore.QRect(10, 10, 291, 261))
        self.mic_group.setObjectName("mic_group")
        self.testmic = None
        self.mic_devices_cobox = QtWidgets.QComboBox(self.mic_group)
        self.mic_devices_cobox.setGeometry(QtCore.QRect(10, 210, 271, 22))
        self.mic_devices_cobox.setObjectName("mic_devices_cobox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Configuration"))
        self.spectrogram_group.setTitle(_translate("Form", "Spectrogram"))
        self.stft_nfft_label.setText(_translate("Form", "N frequencies"))
        self.stft_wtype_label.setText(_translate("Form", "Window type"))
        self.stft_hlength_label.setText(_translate("Form", "Hop length"))
        self.stft_wlength_label.setText(_translate("Form", "Window length"))
        self.log_stft_cbox.setText(_translate("Form", "Use log spectrogram"))
        self.spectrum_group.setTitle(_translate("Form", "Spectrum"))
        self.spectrum_nfft_label.setText(_translate("Form", "N frequencies"))
        self.mic_group.setTitle(_translate("Form", "Microphone"))
import icons_rc
