# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'svccontrol_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SvcControl(object):
    def setupUi(self, SvcControl):
        SvcControl.setObjectName("SvcControl")
        SvcControl.resize(182, 84)
        SvcControl.setMinimumSize(QtCore.QSize(182, 84))
        SvcControl.setMaximumSize(QtCore.QSize(182, 84))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SvcControl.setWindowIcon(icon)
        SvcControl.setLayoutDirection(QtCore.Qt.LeftToRight)
        SvcControl.setStyleSheet("background:white")
        self.centralwidget = QtWidgets.QWidget(SvcControl)
        self.centralwidget.setObjectName("centralwidget")
        self.stop_svc_btn = None
        self.start_svc_btn = None
        SvcControl.setCentralWidget(self.centralwidget)

        self.retranslateUi(SvcControl)
        QtCore.QMetaObject.connectSlotsByName(SvcControl)

    def retranslateUi(self, SvcControl):
        _translate = QtCore.QCoreApplication.translate
        SvcControl.setWindowTitle(_translate("SvcControl", "Service Control"))
import icons_rc
